### ISSUE TITLE
[ErrorCode 19] why my transaction error? 

### ISSUE THREAD

**Issue by weixuefeng** [sei-protocol/sei-chain#1053] opened 2023-09-18 15:45 UTC
when i broadcast my transaction, i got message
```
{tx_response: {height: 0, txhash: 3485B07AA0A8267F64C8C05A4545BD8F06154A5D838567250484BD0226B1B34D, codespace: sdk, code: 19, data: , raw_log: , logs: [], info: , gas_wanted: 0, gas_used: 0, tx: null, timestamp: , events: []}}
```
so, why my transaction error?

**Comment by duncand0nuts** [comment] 2023-09-27 19:20
Hi @weixuefeng, I will take a look at this for you. To help me investigate this issue, please could you provide the following:

**Seid version**
Show us output of `seid version --long | head`

**Chain ID**
Which chain are you running into issues with?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by duncand0nuts** [comment] 2023-10-04 14:16
Hi @weixuefeng 👋 I am closing this issue now as it has been more than 7 days since we have heard from you. If you still need assistance, please comment on this issue (preferably with the information detailed in my previous comment).

**Closed by duncand0nuts** 2023-10-04 14:16 UTC
Labels: bug
