### ISSUE TITLE
[BUG] local chain can't run

### ISSUE THREAD

**Issue by SteveMBao** [sei-protocol/sei-chain#1033] opened 2023-08-21 09:15 UTC
**Seid version**
name: sei
server_name: <appd>
version: 3.0.8
commit: 605ce0378a0429f04032f095e64ddca014a7128b
build_tags: netgo ledger,
go: go version go1.20.7 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/CosmWasm/wasmd@v0.27.0 => github.com/sei-protocol/sei-wasmd@v0.0.2

**Chain ID**
sei-chain

**Describe the bug**
I'm follow [Guide](https://docs.sei.io/develop/developer-tools/local-sei-node) to run a local node,  use ./scripts/initialize_local_chain.sh script, but got error:

sed: can't read s/mode = "full"/mode = "validator"/g: No such file or directory

my os is pop-os 22.04 LTS forked Ubuntu

**Screenshots**
![image](https://github.com/sei-protocol/sei-chain/assets/17777077/70e0a421-1230-4e4a-9182-f5198f25e730)

**Comment by yzang2019** [comment] 2023-08-23 16:34
Can you check if your config file exists under ~/.sei/config/config.toml?

**Comment by SteveMBao** [comment] 2023-08-24 00:12
it's exists , I found code bug in .sh file L43~L44:
```bash
sed -i '' 's/mode = "full"/mode = "validator"/g' $HOME/.sei/config/config.toml
sed -i '' 's/indexer = \["null"\]/indexer = \["kv"\]/g' $HOME/.sei/config/config.toml
```
I'm comment this code and manual to modified config.toml file, it's works.

could you or teams please review it on pop-os/Ubuntu 22.04 again?

**Comment by SteveMBao** [comment] 2023-08-24 00:15
BTW,  in this [GUIDE](https://docs.sei.io/develop/get-started/counter-smart-contract-tutorial)
and this [Guide](https://docs.sei.io/develop/get-started/spot-exchange-tutorial)
Paste the following code into deploy.sh
 --fees=300000usei need change to --fees=3000000usei

**Comment by philipsu522** [comment] 2023-08-29 16:35
Thanks for the fix to the script @SteveMBao!
@LCyson can you provide guidance for the second issue

**Comment by codebycarson** [comment] 2023-08-29 17:12
@SteveMBao did you by chance run your contract through the rust optimizer?
https://github.com/CosmWasm/rust-optimizer

This could be the cause of your high gas prices.

**Comment by SteveMBao** [comment] 2023-08-29 23:59
@codebycarson thanks mate, might I'm used docker image to optimizer "counter" contract, team can close this issue when fix it

**Comment by philipsu522** [comment] 2023-08-30 15:35
@SteveMBao we'll go ahead and close this now, let us know if you still have issues

**Closed by philipsu522** 2023-08-30 15:35 UTC
Labels: bug
