### ISSUE TITLE
[SEI-5644] Testnet deployment does not work even though i follow the documentation

### ISSUE THREAD

**Issue by devine200** [sei-protocol/sei-chain#1058] opened 2023-09-20 09:14 UTC
This is the deployment command i used
```bash
seid tx wasm store artifacts/spot_lite.wasm -y --from=admin --chain-id=atlantic-2 --node https://rest.atlantic-2.seinetwork.io/ --gas=2000000 --fees=20000usei --broadcast-mode=block
```
This is the error i get
```bash 
Error: unmarshaling response test: cannot decode empty bytes, bytes: 0
```

<sub>[SEI-5644](https://linear.app/seilabs/issue/SEI-5644/testnet-deployment-does-not-work-even-though-i-follow-the)</sub>

**Comment by duncand0nuts** [comment] 2023-09-27 19:23
Hi @devine200 👋 
I will look into this for you. To help me, could you please provide the following?

**Seid version**
Show us output of `seid version --long | head`

**Chain ID**
Which chain are you running into issues with?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by duncand0nuts** [comment] 2023-10-04 14:15
Hi @devine200 👋 I am closing this issue now as it has been more than 7 days since we have heard from you. If you still need assistance, please comment on this issue (preferably with the information detailed in my previous comment).

**Closed by duncand0nuts** 2023-10-04 14:15 UTC
Labels: bug, linear
